# Generated by Django 5.1.4 on 2025-02-08 20:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0002_remove_doctor_creator'),
        ('patientcares', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientcare',
            name='location',
        ),
        migrations.AddField(
            model_name='patientcare',
            name='city',
            field=models.CharField(default='Guanambi - Bahia', max_length=40),
        ),
        migrations.AddField(
            model_name='patientcare',
            name='district',
            field=models.CharField(default='Bairro', max_length=40),
        ),
        migrations.AddField(
            model_name='patientcare',
            name='number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientcare',
            name='street',
            field=models.CharField(default='Rua', max_length=64),
        ),
        migrations.RemoveField(
            model_name='patientcare',
            name='doctor',
        ),
        migrations.AddField(
            model_name='patientcare',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='doctors.doctor'),
        ),
    ]
