# Generated by Django 5.1.4 on 2025-02-08 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0001_initial'),
        ('patientcares', '0002_remove_patientcare_location_patientcare_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientcare',
            name='medicine',
            field=models.ManyToManyField(blank=True, to='medicines.medicine'),
        ),
    ]
