# Generated by Django 5.0.1 on 2024-11-17 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('dosage', models.CharField(max_length=10)),
                ('manufacturer', models.CharField(max_length=40, null=True)),
                ('composition', models.CharField(max_length=40, null=True)),
                ('medicine_image', models.ImageField(upload_to='medicines/')),
            ],
        ),
    ]
