# Generated by Django 5.1.4 on 2025-02-09 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='medicine_image',
            field=models.ImageField(blank=True, upload_to='medicines/'),
        ),
    ]
